"""adiciona cache de analise por texto para evitar chamada repetida ao gemini

Revision ID: 148d6f91c829
Revises: 24647c500ae5
Create Date: 2026-07-28 09:56:28.248380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148d6f91c829'
down_revision = '24647c500ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_analysis_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description_hash', sa.String(length=64), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('text_analysis_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_analysis_cache_description_hash'), ['description_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_analysis_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_analysis_cache_description_hash'))

    op.drop_table('text_analysis_cache')
    # ### end Alembic commands ###
