"""adiciona indice em favorite_meals.user_id

Revision ID: 24647c500ae5
Revises: 7c141a5cfcca
Create Date: 2026-07-27 20:51:44.002975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24647c500ae5'
down_revision = '7c141a5cfcca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_meals_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_meals_user_id'))

    # ### end Alembic commands ###
