"""add name column ao food_cache para busca no catalogo

Revision ID: 562297993ad0
Revises: ccd799a1b509
Create Date: 2026-07-26 11:47:47.408610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562297993ad0'
down_revision = 'ccd799a1b509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # Backfill: linhas existentes só tinham o search_query normalizado.
    # Usa como nome de exibição provisório até a próxima vez que o alimento
    # for analisado (quando o nome original com acentos/maiúsculas é salvo).
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE food_cache SET name = search_query WHERE name IS NULL"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_cache', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
