"""adiciona progress_photos para fotos de progresso lado a lado

Revision ID: 56947b4fde03
Revises: f6623acbfcbf
Create Date: 2026-07-29 12:27:54.882486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56947b4fde03'
down_revision = 'f6623acbfcbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('taken_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'taken_at', name='uq_progress_photos_user_taken_at')
    )
    with op.batch_alter_table('progress_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_photos_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_photos_user_id'))

    op.drop_table('progress_photos')
    # ### end Alembic commands ###
