"""add quantity_g to meals

Revision ID: 87d3c5d1abc4
Revises: ced057c4e347
Create Date: 2026-07-23 19:21:20.030860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d3c5d1abc4'
down_revision = 'ced057c4e347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_g', sa.Float(), nullable=False, server_default='100'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_column('quantity_g')

    # ### end Alembic commands ###
