"""add food_cache table

Revision ID: b6bbbaf3bafa
Revises: c400242b857f
Create Date: 2026-07-24 09:35:58.720447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bbbaf3bafa'
down_revision = 'c400242b857f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_cache_search_query'), ['search_query'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_cache_search_query'))

    op.drop_table('food_cache')
    # ### end Alembic commands ###
