"""add weekly plans (segunda a domingo) e goal_type em user_goals

Revision ID: ccd799a1b509
Revises: d74de170dc9d
Create Date: 2026-07-25 18:45:13.106541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd799a1b509'
down_revision = 'd74de170dc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('split_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['split_id'], ['workout_splits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('weekly_plan_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('split_day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['weekly_plans.id'], ),
    sa.ForeignKeyConstraint(['split_day_id'], ['split_days.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'day_of_week', name='uq_weekly_plan_day')
    )
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_type', sa.String(length=20), nullable=False, server_default='maintain'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_column('goal_type')

    op.drop_table('weekly_plan_days')
    op.drop_table('weekly_plans')
    # ### end Alembic commands ###
