"""migracao inicial

Revision ID: ced057c4e347
Revises: 
Create Date: 2026-07-22 11:09:47.619063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced057c4e347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('goal_protein_g')
        batch_op.drop_column('goal_fat_g')
        batch_op.drop_column('goal_calories')
        batch_op.drop_column('goal_carbs_g')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_carbs_g', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('goal_calories', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('goal_fat_g', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('goal_protein_g', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
