"""adiciona indice composto em workouts user_id started_at

Revision ID: d632ba8cecfd
Revises: c767fb8713e3
Create Date: 2026-07-29 10:46:06.851426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd632ba8cecfd'
down_revision = 'c767fb8713e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index('ix_workouts_user_id_started_at', ['user_id', 'started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index('ix_workouts_user_id_started_at')

    # ### end Alembic commands ###
