"""add workout splits (bro split, abcd, ppl, upper-lower, full body)

Revision ID: d74de170dc9d
Revises: de34e46399fb
Create Date: 2026-07-25 17:20:59.295397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74de170dc9d'
down_revision = 'de34e46399fb'
branch_labels = None
depends_on = None


# Divisões de treino pré-cadastradas: (split_id, split_name, split_description)
SPLITS = [
    (1, "Full Body", "Corpo inteiro em cada sessão."),
    (2, "Upper/Lower", "Alterna superior e inferior."),
    (3, "Push/Pull/Legs", "Empurrar, puxar e pernas."),
    (4, "ABCD", "Quatro dias, grupos combinados."),
    (5, "Bro Split", "Um grupo muscular por dia."),
]

# Dias: (day_id, split_id, name, order, [nomes de exercícios sugeridos, na ordem])
DAYS = [
    (1, 1, "Corpo Inteiro", 0, [
        "Agachamento Livre", "Supino Reto", "Remada Curvada",
        "Desenvolvimento Militar", "Rosca Direta", "Abdominal Supra",
    ]),
    (2, 2, "Superior", 0, [
        "Supino Reto", "Remada Curvada", "Desenvolvimento Militar",
        "Puxada Frontal", "Rosca Direta", "Tríceps Corda",
    ]),
    (3, 2, "Inferior", 1, [
        "Agachamento Livre", "Leg Press", "Cadeira Extensora",
        "Mesa Flexora", "Panturrilha em Pé", "Abdominal Supra",
    ]),
    (4, 3, "Push", 0, [
        "Supino Reto", "Supino Inclinado", "Desenvolvimento Militar",
        "Elevação Lateral", "Tríceps Corda",
    ]),
    (5, 3, "Pull", 1, [
        "Puxada Frontal", "Remada Curvada", "Remada Baixa",
        "Rosca Direta", "Rosca Martelo",
    ]),
    (6, 3, "Legs", 2, [
        "Agachamento Livre", "Leg Press", "Cadeira Extensora",
        "Mesa Flexora", "Panturrilha em Pé",
    ]),
    (7, 4, "A - Peito e Tríceps", 0, [
        "Supino Reto", "Supino Inclinado", "Crossover",
        "Tríceps Corda", "Tríceps Testa",
    ]),
    (8, 4, "B - Costas e Bíceps", 1, [
        "Puxada Frontal", "Remada Curvada", "Remada Baixa",
        "Rosca Direta", "Rosca Alternada",
    ]),
    (9, 4, "C - Pernas", 2, [
        "Agachamento Livre", "Leg Press", "Cadeira Extensora",
        "Mesa Flexora", "Panturrilha em Pé",
    ]),
    (10, 4, "D - Ombro e Core", 3, [
        "Desenvolvimento Militar", "Elevação Lateral", "Elevação Frontal",
        "Abdominal Supra", "Prancha Isométrica",
    ]),
    (11, 5, "Peito", 0, ["Supino Reto", "Supino Inclinado", "Crucifixo", "Crossover"]),
    (12, 5, "Costas", 1, ["Puxada Frontal", "Remada Curvada", "Remada Baixa", "Barra Fixa"]),
    (13, 5, "Pernas", 2, [
        "Agachamento Livre", "Leg Press", "Cadeira Extensora",
        "Mesa Flexora", "Panturrilha em Pé",
    ]),
    (14, 5, "Ombros", 3, ["Desenvolvimento Militar", "Elevação Lateral", "Elevação Frontal"]),
    (15, 5, "Braços", 4, [
        "Rosca Direta", "Rosca Alternada", "Rosca Martelo",
        "Tríceps Corda", "Tríceps Testa",
    ]),
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('split_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['split_id'], ['workout_splits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split_day_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('split_day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['split_day_id'], ['split_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_day_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_workouts_split_day_id', 'split_days', ['split_day_id'], ['id'])

    # ### end Alembic commands ###

    # --- Seed: divisões, dias e exercícios sugeridos ---
    conn = op.get_bind()

    conn.execute(
        sa.text("INSERT INTO workout_splits (id, name, description) VALUES (:id, :name, :description)"),
        [{"id": s[0], "name": s[1], "description": s[2]} for s in SPLITS],
    )

    conn.execute(
        sa.text("INSERT INTO split_days (id, split_id, name, \"order\") VALUES (:id, :split_id, :name, :order)"),
        [{"id": d[0], "split_id": d[1], "name": d[2], "order": d[3]} for d in DAYS],
    )

    # Resolve o exercise_id de cada nome sugerido consultando a tabela já seedada.
    exercise_rows = conn.execute(sa.text("SELECT id, normalized_name FROM exercises")).fetchall()
    exercise_id_by_name = {row[1]: row[0] for row in exercise_rows}

    day_exercise_values = []
    for day_id, _split_id, _name, _order, exercise_names in DAYS:
        for position, exercise_name in enumerate(exercise_names):
            exercise_id = exercise_id_by_name.get(exercise_name.strip().lower())
            if exercise_id is None:
                continue
            day_exercise_values.append({
                "split_day_id": day_id,
                "exercise_id": exercise_id,
                "order": position,
            })

    conn.execute(
        sa.text(
            "INSERT INTO split_day_exercises (split_day_id, exercise_id, \"order\") "
            "VALUES (:split_day_id, :exercise_id, :order)"
        ),
        day_exercise_values,
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_workouts_split_day_id', type_='foreignkey')
        batch_op.drop_column('split_day_id')

    op.drop_table('split_day_exercises')
    op.drop_table('split_days')
    op.drop_table('workout_splits')
    # ### end Alembic commands ###
