"""adiciona indices em meals, workouts, set_logs e weight_logs

Revision ID: dc307cefcd46
Revises: 562297993ad0
Create Date: 2026-07-27 18:38:17.140496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc307cefcd46'
down_revision = '562297993ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index('ix_meals_user_id_created_at', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_set_logs_workout_id'), ['workout_id'], unique=False)

    with op.batch_alter_table('weight_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workouts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workouts_user_id'))

    with op.batch_alter_table('weight_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_logs_user_id'))

    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_set_logs_workout_id'))

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index('ix_meals_user_id_created_at')

    # ### end Alembic commands ###
