"""add workout module tables (exercises, workouts, set_logs)

Revision ID: de34e46399fb
Revises: b6bbbaf3bafa
Create Date: 2026-07-25 15:01:18.138191

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de34e46399fb'
down_revision = 'b6bbbaf3bafa'
branch_labels = None
depends_on = None


# Catálogo inicial de exercícios (seed) — cobre os principais grupos musculares.
# is_custom=False marca esses como pré-cadastrados (não criados por um usuário).
SEED_EXERCISES = [
    ("Supino Reto", "barra", "peito"),
    ("Supino Inclinado", "halteres", "peito"),
    ("Crucifixo", "halteres", "peito"),
    ("Crossover", "cabo", "peito"),
    ("Puxada Frontal", "polia", "costas"),
    ("Remada Curvada", "barra", "costas"),
    ("Remada Baixa", "cabo", "costas"),
    ("Barra Fixa", "peso do corpo", "costas"),
    ("Agachamento Livre", "barra", "perna"),
    ("Leg Press", "máquina", "perna"),
    ("Cadeira Extensora", "máquina", "perna"),
    ("Mesa Flexora", "máquina", "perna"),
    ("Panturrilha em Pé", "máquina", "perna"),
    ("Desenvolvimento Militar", "barra", "ombro"),
    ("Elevação Lateral", "halteres", "ombro"),
    ("Elevação Frontal", "halteres", "ombro"),
    ("Rosca Direta", "barra", "braço"),
    ("Rosca Alternada", "halteres", "braço"),
    ("Rosca Martelo", "halteres", "braço"),
    ("Tríceps Corda", "cabo", "braço"),
    ("Tríceps Testa", "barra", "braço"),
    ("Abdominal Supra", "peso do corpo", "core"),
    ("Prancha Isométrica", "peso do corpo", "core"),
    ("Elevação de Pernas", "peso do corpo", "core"),
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=120), nullable=False),
    sa.Column('muscle_group', sa.String(length=30), nullable=False),
    sa.Column('equipment', sa.String(length=50), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_normalized_name'), ['normalized_name'], unique=True)

    exercises_table = sa.table(
        'exercises',
        sa.column('name', sa.String),
        sa.column('normalized_name', sa.String),
        sa.column('muscle_group', sa.String),
        sa.column('equipment', sa.String),
        sa.column('is_custom', sa.Boolean),
        sa.column('created_at', sa.DateTime),
    )
    now = datetime.utcnow()
    op.bulk_insert(exercises_table, [
        {
            "name": name,
            "normalized_name": name.strip().lower(),
            "muscle_group": muscle_group,
            "equipment": equipment,
            "is_custom": False,
            "created_at": now,
        }
        for name, equipment, muscle_group in SEED_EXERCISES
    ])

    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_logs')
    op.drop_table('workouts')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_normalized_name'))

    op.drop_table('exercises')
    # ### end Alembic commands ###
