"""adiciona items em favorite_meals para pratos compostos

Revision ID: f6623acbfcbf
Revises: d632ba8cecfd
Create Date: 2026-07-29 12:14:23.511791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6623acbfcbf'
down_revision = 'd632ba8cecfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_meals', schema=None) as batch_op:
        batch_op.drop_column('items')

    # ### end Alembic commands ###
